version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: sudo npm i -g yarn
      - run: yarn
      - run: yarn test
